server:
  port: 8080

spring:
  application:
    name: booking

  # Cấu hình kết nối cơ sở dữ liệu Supabase PostgreSQL
  datasource:
    url: jdbc:postgresql://db.kxsassyoimnekfduihub.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: sy4B3CAFjoxnDtL4
    driver-class-name: org.postgresql.Driver

  # Cấu hình Hibernate JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Tự động tạo/cập nhật bảng khi chạy thử dự án
    show-sql: true # In câu lệnh SQL ra console để debug
    properties:
      hibernate:
        format_sql: true

# Cấu hình khóa JWT từ Supabase phục vụ giải mã Token bảo mật
supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET:mcDvrnb1GX2lC2GGmq/b6U7dWHwwjIM94/irydzgZdDP9mPQVN7FOgbfBSdEJWKQ1gl/ds0dVpDv1UzvDg/uTQ==}
